// NOTE: copied from root utils/keys.js (contains EMSI credentials)
const emsi = () => [
  { client: 'jroe9ppfuic1bzvt', secret: 'usyUNfg6' },
  { client: 'jbdfa879tu3fjf2w', secret: 'oIUoscZQ' },
  { client: 'jbdfa879tu3fjf2w', secret: 'oIUoscZQ' },
  { client: 'uj7738m3vmfvbi6u', secret: 'Y9zXgyA4' },
  { client: 'r2apqxhojqd7k3sd', secret: 'xMlqvjoA' },
  { client: 'ghevtfldnfa4nits', secret: 'SKeXrW9U' },
  { client: '6flxl9lkmwj5eohe', secret: '4Iksb3NA' },
  { client: 'kkpgm0vtebhjkosb', secret: '9Qy30Hx2' },
  { client: 'ravletg9c2t2h7ff', secret: 'moDpsWav' },
  { client: 'si34j7127zm1o9sr', secret: '1vuR0dCb' },
  { client: 'm46vecvtqj3lckn0', secret: 'xCN3Mxn6' },
  { client: '85eujv6f8f21zfhc', secret: '4LHf40wS' },
  { client: '9yk1g261p7g2t0i5', secret: 'jwZU31SB' },
  { client: 'qcjg10etn9qctsf5', secret: 'OUjSVBTD' },
  { client: '4ww3czvftfif4kpw', secret: 'ITswNHuC' },
  { client: 'q748vs3rlgltgrsk', secret: 'NsYivyQg' },
  { client: 'jpip3p686thssrfh', secret: 'RRwAkm3d' },
  { client: 'h99r839sf2hvnveq', secret: 'ZnUGEpoC' },
  { client: 'ij4t48a91zkw30tq', secret: 'G1sWyMUo' },
  { client: 'omvt0kns4wewr1sh', secret: '0aZb3T8T' },
  { client: '80cx9fihdo8aceqv', secret: 'EEWZrI1i' },
  { client: 'guntc5o6ib9mqb8x', secret: '0ItWAUes' },
  { client: '6tokckyk2e7cgilf', secret: 'EUbAIeKO' },
  { client: 'b4gabbxyfmnp0bus', secret: 'QQODWzzv', scope: 'emsi_open' },
  { client: 'tzdjkr6akvgkxdmo', secret: 'QB3rtACu', scope: 'emsi_open' },
  { client: 'tzdjkr6akvgkxdmo', secret: 'QB3rtACu', scope: 'emsi_open' },
  { client: 'd41nsww2xml7wm3e', secret: 'C4LLBeVp', scope: 'emsi_open' },
  { client: '74x7zmozmz8fiqud', secret: '6stwSF9B', scope: 'emsi_open' },
  { client: 'duwgu3vuhlbr3vj2', secret: 'RWY09R8M', scope: 'emsi_open' },
  { client: '9doiv2cmqlaf9r0f', secret: 'KTefV00m', scope: 'emsi_open' },
  { client: 'otela8rzydlupz9t', secret: 'Bv1Bg7aT', scope: 'emsi_open' },
  { client: 'vcb8mg0r0cv9czh5', secret: 'eIDhuFAx', scope: 'emsi_open' },
  { client: 'uetvuc2n9d3y6c6n', secret: 'NZXCv5rY', scope: 'emsi_open' },
  { client: 'mww07yotuhjhpm83', secret: 'aLb2mlyE', scope: 'emsi_open' },
  { client: 'mo0mj1y4jsjr32x0', secret: 'cywLynCL', scope: 'emsi_open' },
  { client: 'jb8buspllvp5yvm2', secret: 'am3FJllo', scope: 'emsi_open' },
  { client: '7by8hmob2j3s2j72', secret: 'BeaP23rQ', scope: 'emsi_open' },
  { client: 'gt3urc7jhw43j81b', secret: 'y83KG4I4', scope: 'emsi_open' },
  { client: '24oqu4cfzzvmfmyq', secret: '3pBUEqet', scope: 'emsi_open' },
  { client: '24oqu4cfzzvmfmyq', secret: '3pBUEqet', scope: 'emsi_open' },
  { client: '7by8hmob2j3s2j72', secret: 'BeaP23rQ', scope: 'emsi_open' },
  { client: 'hzj5ffgrxe0asc12', secret: 'HkY62TEj', scope: 'emsi_open' },
  { client: 'gt3urc7jhw43j81b', secret: 'y83KG4I4', scope: 'emsi_open' },
  { client: 'a397xmzq9xhq5u83', secret: 'cRsKirM9', scope: 'emsi_open' },
  { client: 'r6tueqfc2eglnvbh', secret: '41QN7WBO', scope: 'emsi_open' },
  { client: '036ayc1nj9e04brj', secret: 'VMdvQO6i', scope: 'emsi_open' },
  { client: '5f379hywuvh7fvan', secret: 'hfCkXQEy', scope: 'emsi_open' },
  { client: 'n7gpmbt9bmj5f4mg', secret: 'tYx0dFGv', scope: 'emsi_open' },
  { client: 'xmqcyxcit195k0bq', secret: 'VQoBI2PQ', scope: 'emsi_open' },
  { client: '980nnwk4cnlxk6u4', secret: 'imo3ndvA', scope: 'emsi_open' },
  { client: 'u2e1c3ba8oh9v16r', secret: 'Kd3uFDeG', scope: 'emsi_open' },
  { client: 'zmjv32jntsjkv9tg', secret: 'rh9xc2Za', scope: 'emsi_open' },
  { client: 'yyvc3w5wlnnb3pjw', secret: 'Sa2S3F1h', scope: 'emsi_open' }
];

module.exports = {
  emsi,
};

